//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkCodeFirst.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int PatientID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> FHNId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<int> NursingAgencyId { get; set; }
        public int AgencyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<decimal> ToBeCollected_ { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.TimeSpan> OrderTime { get; set; }
        public string CCACPO { get; set; }
        public Nullable<System.DateTime> DatePromised { get; set; }
        public Nullable<System.TimeSpan> TimePromised { get; set; }
        public string OrderNote { get; set; }
        public Nullable<decimal> Collected_ { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public Nullable<System.TimeSpan> TimeDelivered { get; set; }
        public string SalesPerson { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<System.DateTime> OrdDatePaid { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<bool> Audited { get; set; }
        public Nullable<decimal> OrderDelCost { get; set; }
        public string DeliverNote { get; set; }
        public Nullable<int> DeliveryFailureReason { get; set; }
        public string DeliveryFailureComments { get; set; }
        public Nullable<bool> PrescriptionIncluded { get; set; }
        public Nullable<bool> HazardousMaterials { get; set; }
        public Nullable<bool> Refrigerate { get; set; }
        public string CCACOrderType { get; set; }
        public Nullable<int> PMILinkId { get; set; }
        public string BilltoAgency { get; set; }
        public string Terms { get; set; }
        public string ShipVia { get; set; }
        public string OrderedBy { get; set; }
        public Nullable<byte> DeliveryCategory { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<System.DateTime> DatePickup { get; set; }
        public Nullable<System.TimeSpan> TimePickup { get; set; }
        public Nullable<System.DateTime> SPPaymentDate { get; set; }
        public Nullable<bool> ynPaySP { get; set; }
        public Nullable<bool> ynUpdateDeliveryDate { get; set; }
        public Nullable<short> StatusId { get; set; }
    
        public virtual Patient tblPatient { get; set; }
    }
}
